### ISSUE TITLE
Publish on PyPI automatically with GitHub Action when a release is created

### ISSUE THREAD

**Issue by mattwang44** [yychen/dj-registry#1]
This issue proposes automating the process of publishing this package to PyPI using GitHub Action, which should not be hard to be implemented by using [`twine`](https://github.com/pypa/twine) or [`poetry publish`](https://python-poetry.org/docs/cli/#publish) in the workflow. An example of publishing package using `twine` can be found in [`poutils`](https://github.com/AFPy/poutils/blob/master/.github/workflows/python-publish.yml) and there is a [public action for `poetry publish`](https://github.com/marketplace/actions/publish-python-poetry-package) can be found in GitHub marketplace.

**Comment by mattwang44** [comment]
@yychen The PR for fulfilling this feature request is sent but the workflow required permission to upload the package to PyPI. Please help us insert the PyPI API token as a secret (with `PYPI_TOKEN` as key) of this repo. 

You should be able to:
- Add a new PyPI API token [here](https://pypi.org/manage/account/token/). (Creating a new project-specific token for this workflow is recommended.)
- Add a new secret to this repo [here](https://github.com/yychen/dj-registry/settings/secrets/actions/new).

**Comment by yychen** [comment]
Thanks for the heads up, the instructions are very clear. Please take a look if I did it right (or not).

Thanks!

**Comment by mattwang44** [comment]
@yychen I've verified the PR works correctly in my forked repo but [the release action in this repo has failed](https://github.com/yychen/dj-registry/runs/5331037530) (it says the action cannot find the key). Would you please check again if you add the token to repo secrets (rather than env secrets)? (or you can grant me permission to the page by temporarily setting me as the repo admin).

![image](https://user-images.githubusercontent.com/24987826/155684935-0c764f5d-3b5f-4d2c-b101-2504f3160ad6.png)

**Comment by yychen** [comment]
I am very sorry. I missed out "(with PYPI_TOKEN as key)". I updated the setting and re-run the action. It worked like a charm. Thanks @mattwang44
